<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class ProllEmployeeInfo extends Model
{
    protected $table = 'proll_employee_info';
    protected $fillable = [
        'sub_department_level1_id',
        'sub_department_level2_id',
        'shift_id',
        'weekend_day_id',
        'father_occupation',
        'father_dob',
        'hrms_id',
        'unique_position_id',
        'date_of_rejection',
        'hr_email_id',
        'hom_address',
        'postalcode',
        'country', 
        'second_nationality_id',
        'domicile_country_id',
        'domicile_city_id',
        'religion_id',
        'cast',
        'city',
        'location',
        'hom_phone',
        'cell_number',
        'm_status',
        'no_of_dependants',
        'fs_report',
        'reason',
        'imp_id', 
        'fs_status', 
        'birth_country_id',
        'birth_city_id',
        'visa_image',
        'visa_expiry',
        'degree_image',
        'dob',
        'added', 
        'alert_sent',
        'passport_alert_sent',
        'visa_alert_sent',
        'cnic_alert_sent',
        'loggedin', 
        'bg_img',
        'bg_color',
        'emp_band',
        'contract_status',
        'contract_expiry',
        'assist_id',
        'reasonforleaving',
        'view_status',
        'alm_view_status',
        'lm_view_status',
        'hr_view_status',
        'blood_group_name',
        'portal_id',
        'user_id',
        'employee_height',
        'employee_weight', 
        'native_language_id',
        'ntn_number',
        'ntn_country_id',
        'ntn_status',
        'ex_employee_flag',
        'ex_employee_code',
        'nomination_agree_check',
        'ex_relevent_experience_flag',
        'experience_with_client_flag',
        'ex_inquire_objection_flag',
        'ex_inquire_objection_detail',
        'serious_ailment_flag',
        'serious_ailment_brief',
        'arrested_flag',
        'arrested_brief',
        'created_at', 
        'created_by',
        'updated_at', 
        'updated_by',
        'employment_file',
        'allow_policy_manual',
        'remember_token',
        'main_lm', 
        'contract_start_date',
        'contract_end_date',
        'in_active_type',
        'leave_bank_updated', 
        'is_mobile_attendance',
        'remote_attendance_allowed',
        'gender',
        'birth_state_id',
        'domicile_state_id'
    ];
    public $timestamps = false;
}

